### ISSUE TITLE
Invalid interpolation format

### ISSUE THREAD

**Issue by minhduc19** [nickjj/docker-node-example#1]
Hi Nick, 

When I try to run `docker-compose up --build `, I got this error: 

`ERROR: Invalid interpolation format for "build" option in service "x-app": "NODE_ENV=${NODE_ENV:-production}"`

Do you think this is a problem about docker version?

Many thanks

**Comment by nickjj** [comment]
Hi,

What version of Docker Compose do you have? You can check with `docker-compose --version`.

It sounds like you might have an old version (years old) which doesn't support `export` , but 1.26+ supports that so if you upgrade to at least 1.26+ then you should be good to go.

**Comment by minhduc19** [comment]
Hi,

Yes, that's the problem! I run it on online Docker lab and assumed they have the latest version of Docker compose. Obviously, it was not!

**Comment by nickjj** [comment]
I should probably mention this in the readme because it's come up twice already in the other example app repos.

Thanks for the report!
